### ISSUE TITLE
how to link with opencv4?

### ISSUE THREAD

**Issue by jjqcat** [cpvrlab/SLProject#41]

**Comment by hudrima1** [comment]
If you are using cmake to configure a prebuilt version of OpenCV inclusive contibs will be downloaded and linked automatically. This is done on Windows, MacOS, iOS and Android but not on Linux. See the different WIKI pages for instructions on how to build.
Regard
Marcus

**Comment by hudrima1** [comment]
What do you need from 4.* that is not in 3.4.*?

**Comment by jjqcat** [comment]
ohh, opencv4.0 ONLY need one library and dll, it seems clean

**Comment by hudrima1** [comment]
Solved
