### ISSUE TITLE
unicode character support

### ISSUE THREAD

**Issue by jjqcat** [cpvrlab/SLProject#49]
HI, it's useful project, but SLTexFont doesn't support unicode character font, such as Chinese font (ttf font file as in imgui render), would you help make it perfect? thanks

**Comment by hsm4** [comment]
Hi jjqcat,
we won't do that because will rely in the future fully on ImGui.
This framework evolved extremely well in the past and it most probably handles fonts much better than we would.
Regards
Marcus

**Comment by jjqcat** [comment]
I see, thanks

**Comment by jjqcat** [comment]
other way to solve this issue
